fdfs:
 soTimeout: 30
 connectTimeout: 60
 thumbImage:             #缩略图生成参数
  width: 150
  height: 150
 trackerList:            #TrackerList参数,支持多个
  - 192.168.128.141:22122
 pool:
  max-total: 100
  max-wait-millis: 60
