#####  Demo Config  ####
#fdfs:
#  so-timeout: 1501
#  connect-timeout: 601
#  thumb-image:             #缩略图生成参数
#    width: 150
#    height: 150
#  tracker-list:
#   - 192.168.20.40:22122
#   - 192.168.20.41:22122